name: esquema-parcial-frontend

services:
  frontend:
    build:
      context: .
    environment:
      NODE_ENV: production
      TZ: Europe/Madrid
    container_name: frontend
    ports:
      - 4200:4200
    volumes:
      - ./src:/app/src
      - ./public:/app/public  
    command: npm start
  