name: esquema-parcial-backend

x-backend: &backend
  env_file:
    - .env
  environment:
    - TZ=Europe/Madrid
version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./services:/code/services
      - ./models:/code/models
    command: python /code/services/app.py